project_id = "tnzvhwapfhkhqjgyiomk"

[functions.follow-model]
verify_jwt = false

[functions.model-chat]
verify_jwt = false

[functions.bunny-video-upload]
verify_jwt = false

[functions.trigger-webhook]
verify_jwt = false

[functions.hoopay-webhook]
verify_jwt = false
